const main = {
  title: 'Our Missions are Beyond Mars',

  // about_our_lab: migrated to THU-MARS-Web/about_our_lab.vue

  banner: [
    'VCAD.jpg',
    'banner_dubber.jpg',
    'banner3.jpg',
    'banner1.jpg',
    'banner2.jpg',
  ],

  overview_of_research_directions: [
    {
      title: 'Multimedia Computing',
      content: 'We train AI models that learn from multi-modal Internet data such as images, audios, videos and text.',
      image: 'multimedia.png'
    },
    {
      title: 'Autonomous Driving',
      content: 'We develop the next-generation autonomous driving software stack: perception, prediction and planning.',
      image: 'autonomous_vehicles.png'
    },
    {
      title: 'Robotics',
      content: 'We make robots that learn from multiple sensory inputs to interact with the environment.',
      image: 'robotics.png'
    },
    {
      title: 'Sensors',
      content: 'We devise novel sensors together with AI models to enable brand-new perception applications.',
      image: 'sensors.png'
    },
  ],

  about_our_leader: [
    'Dr. Hang Zhao (赵行) is an Assistant Professor at IIIS, Tsinghua University. His research interests include multi-modal machine learning, computer vision and autonomous driving.',
    'Dr. Zhao was formerly a Research Scientist at Waymo (known as Google\'s self-driving project). Before that, he got his Ph.D. degree at MIT under the supervision of Professor Antonio Torralba.'
  ],

  graduate_students: [
    {
      name: 'Chenzhuang Du 杜晨壮',
      website: 'https://scholar.google.com/citations?user=VoF-UAEAAAAJ&hl=en',
      content: 'Chenzhuang Du is a PhD student starting from 2020. He is interested in applications of Foundation Models and multi-modal learning.',
      image: 'chenzhuang.jpeg',
    },
    {
      name: 'Junru Gu 辜俊儒',
      website: 'https://github.com/GentleSmile',
      content: 'Junru Gu is a PhD student starting from 2021. He is interested in autonomous driving.',
      image: 'gujunru.png',
    },
    {
      name: 'Chenxu Hu 胡晨旭',
      website: 'https://huchenxucs.github.io/',
      content: 'Chenxu Hu is a PhD student starting from 2021. He is interested in multi-modal learning, across vision, language and audio.',
      image: 'chenxu.jpeg',
    },
    {
      name: 'Tianyuan Yuan 袁天远',
      website: '',
      content: 'Tianyuan Yuan is a PhD student starting from 2022. He is interested in computer vision and autonomous driving.',
      image: 'yuantianyuan.jpg',
    },
    {
      name: 'Simian Luo 骆思勉',
      website: '',
      content: 'Simian Luo is a MS student starting from 2022. He is interested in Multi-Modal Generation, AIGC, and multi-modal representation learning.',
      image: 'lsm.jpg',
    },
    {
      name: 'Xiaoyu Tian 田晓宇',
      website: '',
      content: 'Xiaoyu Tian is a MS student and an incoming PhD student. He is interested in computer vision and autonomous driving.',
      image: 'kenan.jpeg',
    },
  ],

  research_assistants: [
      {
      name: 'Qiao Sun 孙桥',
      website: 'https://qiaosun.me/',
      content: 'Qiao Sun is a researcher in the lab. He is interested in planning and simulation for autonomous driving.',
      image: 'qiaosun.png', 
    },
    {
      name: 'Ziwen Zhuang 庄子文',
      website: 'https://sites.google.com/view/ziwenzhuang',
      content: 'Ziwen Zhuang is a research assistant in the lab. He is interested in robotics.',
      image: 'ziwen.jpg',
    },
    {
      name: 'Xuan Xiong 熊璇',
      website: '',
      content: 'Xuan Xiong is a research assistant in the lab. She is interested in autonomous driving.',
      image: 'kenan.jpeg',
    },
    {
      name: 'Yicheng Liu 刘毅成',
      website: 'https://scholar.google.com/citations?user=vRmsgQUAAAAJ&hl',
      content: 'Yicheng Liu is a research assistant in the lab, and an incoming PhD student. He is interested in autonomous driving.',
      image: 'yicheng.jpeg',
    },
    {
      name: 'Tao Jiang 江涛',
      website: '',
      content: 'Tao Jiang is a research assistant in the lab. He is interested in autonomous driving.',
      image: 'jiangtao.jpeg',
    },
    {
      name: 'Cynthia Yu 俞秉宏',
      website: '',
      content: 'Cynthia Yu is a research assistant in the lab. She is interested in autonomous driving.',
      image: 'kenan.jpeg',
    },
    {
      name: 'Siting Li 李思婷',
      website: '',
      content: 'Siting Li is an undergraduate intern in the lab. She is interested in multi-modal learning.',
      image: 'kenan.jpeg',
    },
    {
      name: 'Zitian Tang 唐梓天',
      website: 'https://zitiantang.github.io/',
      content: 'Zitian Tang is an undergraduate intern in the lab. He is interested in multi-modal learning.',
      image: 'zitian.jpg',
    },
    {
      name: 'Wenjie Ye 叶闻捷',
      website: '',
      content: 'Wenjie Ye is an undergraduate intern in the lab. He is interested in multi-modal learning.',
      image: 'kenan.jpeg',
    },
    {
      name: 'Shiduo Zhang 张世铎',
      website: '',
      content: 'Shiduo Zhang is an undergraduate intern in the lab. He is interested in robotics.',
      image: 'kenan.jpeg',
    },
    {
      name: 'Jiangtao Yu 于江涛',
      website: 'https://jiangtaoyu.hk',
      content: 'Jiangtao Yu is an undergraduate intern in the lab. He is interested in multi-sensor machine learning.',
      image: 'yujiangtao.png',
    },
    {
      name: 'Zenan Li 李泽楠',
      website: '',
      content: 'Zenan Li is an undergraduate intern in the lab, and an imcoming PhD student. He is interested in multi-modal learning and decision.',
      image: 'kenan.jpeg',
    },
    {
      name: 'Running Zhao 赵闰宁',
      website: '',
      content: 'Running Zhao is a visiting PhD student from the University of Hong Kong. He is interested in Radar signal learning',
      image: 'kenan.jpeg',
    },
  ],
  
  alumni: [
    {
      name: 'Wenxiao Wang 汪文潇',
      website: 'https://wangwenxiao.github.io/',
      content: 'Wenxiao Wang was a MS student from 2020 to 2021. He is now a PhD student at University of Maryland.',
      image: 'wenxiao.jpeg',
    },
    {
      name: 'Renhao Wang 汪仁皓',
      website: 'https://scholar.google.com/citations?user=q4RlE2oAAAAJ&hl=en',
      content: 'Renhao Wang was a research assistnat from 2021 to 2022. He is now a PhD student at UC Berkeley.',
      image: 'kenan.jpeg',
    },

    {
      name: 'Zihui Xue 薛子慧',
      website: 'https://zihuixue.github.io/',
      content: 'Zihui Xue was a research assistant from 2020 to 2021. She is now a PhD student at UT Austin.',
      image: 'zihui.jpeg',
    },
    {
      name: 'Tianyu Hua 华天羽',
      website: 'https://patrickhua.github.io/',
      content: 'Tianyu Hua was a research assistant from 2020 to 2021. He is an incoming PhD student at Stanford University.',
      image: 'tianyu.jpg',
    },
    {
      name: 'Tingle Li 黎庭乐',
      website: 'https://tinglok.netlify.app/',
      content: 'Tingle Li was a research assistant from 2021 to 2022. He is now a PhD student at UC Berkeley.',
      image: 'tingle.jpg',
    },
    {
      name: 'Tianyuan Zhang 张天远',
      website: 'http://tianyuanzhang.com/',
      content: 'Tianyuan Zhang was a research assistant in 2021. He is an incoming PhD student at MIT.',
      image: 'tianyuan.jpg',
    },
    {
      name: 'Zhengqi Gao 高正祺',
      website: 'https://zhengqigao.github.io/',
      content: 'Zhengqi Gao was an intern in 2021. He is now a PhD student at MIT.',
      image: 'zhengqi.png',
    },
    {
      name: 'Qi Li 李祁',
      website: 'https://liqi17thu.github.io/',
      content: 'Qi Li was an undergraduate intern in 2021. He is now a PhD student at UCLA.',
      image: 'qili.jpeg',
    },
    {
      name: 'Bowen Li 李博文',
      website: 'https://vision4robotics.github.io/authors/bowen-li/',
      content: 'Bowen Li was an undergraduate intern in 2022. He is now a PhD student at CMU.',
      image: 'bowenli.jpeg',
    },
    {
      name: 'Sucheng Ren 任苏成',
      website: 'https://oliverrensu.github.io/',
      content: 'Sucheng was an intern in 2021. He is now at MSRA.',
      image: 'sucheng.jpeg',
    },
    {
      name: 'Xuanyao Chen 陈炫耀',
      website: '',
      content: 'Xuanyao Chen was an intern in the lab from 2021 to 2022. He is an incoming PhD student at IIIS, Tsinghua University.',
      image: 'kenan.jpeg',
    },
    {
      name: 'Lingyu Zhu 朱玲玉',
      website: 'https://ly-zhu.github.io/',
      content: 'Lingyu Zhu was a visiting student in 2021 Fall, from Tampere University, Finland.',
      image: 'lingyuzhu.png',
    },
    {
      name: 'Ziyuan Huang 黄子渊',
      website: 'https://huang-ziyuan.github.io/',
      content: 'Ziyuan Huang was a visiting student in 2022, from National University of Singapore.',
      image: 'ziyuan.jpeg',
    },

  ],

  projects: [
    {
      title: 'What Happened 3 Seconds Ago? Inferring the Past with Thermal Imaging',
      publisher: 'CVPR 2023',
      authors: 'Zitian Tang, Wenjie Ye, Wei-Chiu Ma, Hang Zhao',
      description: '"First RGB-Thermal dataset of indoor human motion and a model to estimate 3-second-ago human pose!"',
      paper_link: 'https://arxiv.org/abs/2304.13651',
      extra_link: [
        {
          name: 'Dataset',
  	      link: 'https://github.com/ZitianTang/Thermal-IM',
        },
      ],
      image: 'ThermalIM.png',
    },
    {
      title: 'Neural Map Prior for Autonomous Driving',
      publisher: 'CVPR 2023',
      authors: 'Xuan Xiong, Yicheng Liu, Tianyuan Yuan, Yue Wang, Yilun Wang, Hang Zhao',
      description: '"First learning-based framework that employs a neural representation of global maps to improve local map inference performance for autonomous driving!"',
      paper_link: 'https://arxiv.org/abs/2304.08481',
      project_link: 'https://tsinghua-mars-lab.github.io/neural_map_prior/',
      image: 'neuralmapprior.png',
    },
    {
      title: 'ViP3D: End-to-end Visual Trajectory Prediction via 3D Agent Queries',
      publisher: 'CVPR 2023',
      authors: 'Junru Gu\*, Chenxu Hu\*, Tianyuan Zhang, Xuanyao Chen, Yilun Wang, Yue Wang, Hang Zhao',
      description: '"First vision-based approach to predict future trajectories of agents for autonomous driving!"',
      paper_link: 'https://arxiv.org/abs/2208.01582',
      project_link: 'https://tsinghua-mars-lab.github.io/ViP3D/',
      image: 'vip3d.gif',
    },
    {
      title: 'InterSim: Interactive Traffic Simulation via Explicit Relation Modeling',
      publisher: 'IROS 2022',
      authors: 'Qiao Sun, Xin Huang, Brian C Williams, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2210.14413',
      project_link: 'https://tsinghua-mars-lab.github.io/InterSim/',
      image: 'intersim.png',
    }, 
    {
      title: 'Radio2Speech: High Quality Speech Recovery from Radio Frequency Signals',
      publisher: 'Interspeech 2022',
      authors: 'Running Zhao, Jiangtao Yu, Tingle Li, Hang Zhao\*, Edith C.H. Ngai\*',
      description: '"High-quality speech recovery system for millimeter-wave radar without deafness!"',
      paper_link: 'https://arxiv.org/abs/2206.11066',
      project_link: 'https://zhaorunning.github.io/Radio2Speech/',
      image: 'radio2speech.jpg',
    },
    {
      title: 'M2I: From Factored Marginal Trajectory Prediction to Interactive Prediction',
      publisher: 'CVPR 2022',
      authors: 'Qiao Sun\*, Xin Huang\*, Junru Gu, Brian C. Williams, Hang Zhao',
      description: '"Relationship predictions boost your motion prediction models for interactive predictions!"',
      paper_link: 'https://arxiv.org/abs/2202.118844',
      project_link: 'https://tsinghua-mars-lab.github.io/M2I/',
      image: 'M2I.gif',
    },
    {
      title: 'FUTR3D: A Unified Sensor Fusion Framework for 3D Detection',
      publisher: 'Preprint 2022',
      authors: 'Xuanyao Chen, Tianyuan Zhang, Yue Wang, Yilun Wang, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2203.10642',
      project_link: 'https://tsinghua-mars-lab.github.io/futr3d/',
      image: 'futr3d.png',
    }, 
    {
      title: 'MUTR3D: A Multi-camera Tracking Framework via 3D-to-2D Queries',
      publisher: 'CVPR Workshop on Autonomous Driving 2022',
      authors: 'Tianyuan Zhang, Xuanyao Chen, Yue Wang, Yilun Wang, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2205.00613',
      project_link: 'https://tsinghua-mars-lab.github.io/mutr3d/',
      image: 'mutr3d.png',
    },
    {
      title: 'SEMI: Self-supervised Exploration via Multisensory Incongruity',
      publisher: 'ICRA 2022',
      authors: 'Jianren Wang*, Ziwen Zhuang*, Hang Zhao',
      description: '"Multi-sensory incongruity incentizes RL agents to explore!"',
      paper_link: 'https://arxiv.org/abs/2009.12494',
      project_link: '',
      image: 'SEMI.jpeg',
    }, 
    {
      title: 'HDMapNet: An Online HD Map Construction and Evaluation Framework',
      publisher: 'ICRA 2022, CVPR 2021 Workshop best paper nominee',
      authors: 'Qi Li, Yue Wang, Yilun Wang, Hang Zhao',
      description: '"HD map sensing from onboard sensors!"',
      paper_link: 'https://arxiv.org/abs/2107.06307',
      project_link: 'https://tsinghua-mars-lab.github.io/HDMapNet/',
      image: 'hdmapnet_demo.gif',
      tags: [
        'hot',
      ],
    },
    {
      title: 'Neural Dubber: Dubbing for Videos According to Scripts',
      publisher: 'NeurIPS 2021',
      authors: 'Chenxu Hu, Qiao Tian, Tingle Li, Yuping Wang, Yuxuan Wang, Hang Zhao',
      description: '"First achieve automatic video dubbing computationally by neural network!"',
      paper_link: 'https://arxiv.org/abs/2110.08243',
      project_link: 'https://tsinghua-mars-lab.github.io/NeuralDubber/',
      image: 'neural_dubber.png',
      tags: [
        'hot',
      ],
    },
    {
      title: 'What Makes Multi-Modal Learning Better than Single (Provably)',
      publisher: 'NeurIPS 2021',
      authors: 'Yu Huang, Chenzhuang Du, Zihui Xue, Xuanyao Chen, Hang Zhao, Longbo Huang',
      paper_link: 'https://proceedings.neurips.cc/paper/2021/hash/5aa3405a3f865c10f420a4a7b55cbff3-Abstract.html',
      image: 'mm_better.png',
      tags: [
        'hot',
      ],
    },
    {
      title: 'DETR3D: 3D Object Detection from Multi-view Images via 3D-to-2D Queries',
      publisher: 'CoRL 2021',
      authors: 'Yue Wang, Vitor Campagnolo Guizilini, Tianyuan Zhang, Yilun Wang, Hang Zhao, Justin Solomon',
      description: '"A new paradigm of 3D object detection from 2D images!"',
      paper_link: 'https://openreview.net/pdf?id=xHnJS2GYFDz',
      project_link: '',
      image: 'detr3d.jpeg',
      tags: [
        'hot',
      ],
    },
    {
      title: 'On Feature Decorrelation in Self-Supervised Learning',
      publisher: 'ICCV 2021 Oral',
      authors: 'Tianyu Hua, Wenxiao Wang, Zihui Xue, Yue Wang, Sucheng Ren, Hang Zhao',
      description: '"It reveals the connection between model collapse and feature correlations!"',
      paper_link: 'https://openaccess.thecvf.com/content/ICCV2021/html/Hua_On_Feature_Decorrelation_in_Self-Supervised_Learning_ICCV_2021_paper.html',
      project_link: 'https://tsinghua-mars-lab.github.io/decorr/',
      image: 'decorrelation.jpg',
      tags: [
        'hot',
      ],
    },
	  {
      title: 'Large Scale Interactive Motion Forecasting for Autonomous Driving: The Waymo Open Motion Dataset',
      publisher: 'ICCV 2021 Oral',
      authors: 'Scott Ettinger, Shuyang Cheng, Benjamin Caine, Chenxi Liu, Hang Zhao, Sabeek Pradhan, Yuning Chai, Ben Sapp, Charles Qi, Yin Zhou, Zoey Yang, Aurelien Chouard, Pei Sun, Jiquan Ngiam, Vijay Vasudevan, Alexander McCauley, Jonathon Shlens, Dragomir Anguelov',
	  // description: '"A high-quality interactive motion prediction dataset for autonomous driving!"',
      paper_link: 'https://openaccess.thecvf.com/content/ICCV2021/html/Ettinger_Large_Scale_Interactive_Motion_Forecasting_for_Autonomous_Driving_The_Waymo_ICCV_2021_paper.html',
      project_link: 'https://blog.waymo.com/2021/03/expanding-waymo-open-dataset-with-interactive-scenario-data-and-new-challenges.html',
      image: 'waymo_motion.gif',
      tags: [
        'hot',
      ],
    },
    {
      title: 'Multimodal Knowledge Expansion',
      publisher: 'ICCV 2021',
      authors: 'Zihui Xue, Sucheng Ren, Zhengqi Gao, Hang Zhao',
      description: '"Multimodal data brings knowledge for free!"',
      paper_link: 'https://openaccess.thecvf.com/content/ICCV2021/html/Xue_Multimodal_Knowledge_Expansion_ICCV_2021_paper.html',
      project_link: 'https://tsinghua-mars-lab.github.io/MKE/',
      image: 'mke.png',
    },    
    {
      title: 'DenseTNT: End-to-end Trajectory Prediction from Dense Goal Sets',
      publisher: 'ICCV 2021, Waymo Motion Prediction Challenge Winner',
      authors: 'Junru Gu, Chen Sun, Hang Zhao',
      description: '"A SOTA anchor-free and end-to-end multi-trajectory prediction model"',
      paper_link: 'https://openaccess.thecvf.com/content/ICCV2021/html/Gu_DenseTNT_End-to-End_Trajectory_Prediction_From_Dense_Goal_Sets_ICCV_2021_paper.html',
      project_link: 'https://tsinghua-mars-lab.github.io/DenseTNT/',
      extra_link: [
        {
          name: 'Waymo Challenge Report',
  	      link: 'https://arxiv.org/abs/2106.14160',
        },
      ],
      image: 'densetnt.png',
      tags: [
        'hot',
      ],
    },
    {
      title: 'CVC: Contrastive Learning for Non-parallel Voice Conversion',
      publisher: 'Interspeech 2021 (ISCA travel grant award)',
      authors: 'Tingle Li, Yichen Liu, Chenxu Hu, Hang Zhao',
      description: '"It only requires one-way GAN training for non-parallel voice conversion"',
      paper_link: 'https://www.isca-speech.org/archive/interspeech_2021/li21d_interspeech.html',
      project_link: 'https://tinglok.netlify.app/files/cvc/',
      image: 'CVC.jpg',
    },
    {
      title: 'HDMapGen: A Hierarchical Graph Generative Model of High Definition Maps',
      publisher: 'CVPR 2021',
      authors: 'Lu Mi, Hang Zhao, Charlie Nash, Xiaohan Jin, Jiyang Gao, Chen Sun, Cordelia Schmid, Nir Shavit, Yuning Chai, Dragomir Anguelov',
      paper_link: 'https://openaccess.thecvf.com/content/CVPR2021/html/Mi_HDMapGen_A_Hierarchical_Graph_Generative_Model_of_High_Definition_Maps_CVPR_2021_paper.html',
      image: 'HDMapGen.jpg',
    },
    {
      title: 'TNT: Target-driveN Trajectory Prediction',
      publisher: 'CoRL 2020',
      authors: 'Hang Zhao*, Jiyang Gao*, Tian Lan, Chen Sun, Benjamin Sapp, Balakrishnan Varadarajan, Yue Shen, Yi Shen, Yuning Chai, Cordelia Schmid, Congcong Li, Dragomir Anguelov',
      description: '"A new learning-based framework for multi-trajectory prediction!"',
      paper_link: 'https://arxiv.org/abs/2008.08294',
      project_link: '',
      image: 'tnt.png',
      tags: [
        'hot',
      ],
    },
    {
      title: 'VectorNet: Encoding HD Maps and Agent Dynamics from Vectorized Representation',
      publisher: 'CVPR 2020',
      authors: 'Jiyang Gao, Chen Sun, Hang Zhao, Yi Shen, Dragomir Anguelov, Congcong Li, Cordelia Schmid',
      description: '"A graphical representation of HD maps."',
      paper_link: 'https://openaccess.thecvf.com/content_CVPR_2020/papers/Gao_VectorNet_Encoding_HD_Maps_and_Agent_Dynamics_From_Vectorized_Representation_CVPR_2020_paper.pdf',
      project_link: 'https://blog.waymo.com/2020/05/vectornet.html',
      image: 'vectornet.gif',
      tags: [
        'hot',
      ],
    },
    {
      title: 'Scalability in Perception for Autonomous Driving: Waymo Open Dataset',
      publisher: 'CVPR 2020',
      authors: 'Pei Sun, Henrik Kretzschmar, Xerxes Dotiwalla, Aurelien Chouard, Vijaysai Patnaik, Paul Tsui, James Guo, Yin Zhou, Yuning Chai, Benjamin Caine, Vijay Vasudevan, Wei Han, Jiquan Ngiam, Hang Zhao, Aleksei Timofeev, Scott Ettinger, Maxim Krivokon, Amy Gao, Aditya Joshi, Sheng Zhao, Shuyang Cheng, Yu Zhang, Jonathon Shlens, Zhifeng Chen, Dragomir Anguelov',
      // description: '"One of the largest and most diverse autonomous driving datasets ever released!"',
      paper_link: 'https://arxiv.org/abs/1912.04838',
      project_link: 'https://waymo.com/open/',
      image: 'waymo_od_challenge.jpeg',
      tags: [
        'hot',
      ],
    },
    {
      title: 'The Sound of Motions',
      publisher: 'ICCV 2019',
      authors: 'Hang Zhao, Chuang Gan, Wei-Chiu Ma, Antonio Torralba',
      description: '"Listen to the sound of motions!"',
      paper_link: 'https://arxiv.org/abs/1904.05979',
      project_link: '',
      image: 'sound_of_motions.png',
    },
    // {
    //   title: 'Self-supervised Moving Vehicle Tracking with Stereo Sound',
    //   publisher: 'ICCV 2019',
    //   authors: 'Chuang Gan, Hang Zhao, Peihao Chen, David Cox, Antonio Torralba',
    //   description: '',
    //   paper_link: 'http://openaccess.thecvf.com/content_ICCV_2019/html/Gan_Self-Supervised_Moving_Vehicle_Tracking_With_Stereo_Sound_ICCV_2019_paper.html',
    //   project_link: '',
    //   image: 'stereo_tracking.jpeg',
    // }, 
    {
      title: 'Through-Wall Human Mesh Recovery Using Radio Signals',
      publisher: 'ICCV 2019',
      authors: 'Mingmin Zhao, Yingcheng Liu, Aniruddh Raghu, Hang Zhao, Tianhong Li, Antonio Torralba, Dina Katabi',
      description: '',
      paper_link: 'http://openaccess.thecvf.com/content_ICCV_2019/html/Zhao_Through-Wall_Human_Mesh_Recovery_Using_Radio_Signals_ICCV_2019_paper.html',
      project_link: '',
      image: 'rfavatar.gif',
    }, 
    {
      title: 'HACS: Human Action Clips and Segments Dataset for Recognition and Temporal Localization',
      publisher: 'ICCV 2019',
      authors: 'Hang Zhao, Zhicheng Yan, Lorenzo Torresani, Antonio Torralba',
      description: '"A large-scale dataset for temporal action localization and recognition."',
      paper_link: 'https://arxiv.org/abs/1712.09374',
      project_link: 'http://hacs.csail.mit.edu/',
      image: 'slac.jpeg',
    }, 
    {
      title: 'The Sound of Pixels',
      publisher: 'ECCV 2018',
      authors: 'Hang Zhao, Chuang Gan, Andrew Rouditchenko, Carl Vondrick, Josh McDermott, Antonio Torralba',
      description: '"Listen to the sound of pixels!"',
      paper_link: 'https://arxiv.org/abs/1804.03160',
      project_link: 'http://sound-of-pixels.csail.mit.edu/',
      image: 'sound_of_pixels.png',
      tags: [
        'hot',
      ],
    }, 
    {
      title: 'RF-Based 3D Skeletons',
      publisher: 'SIGCOMM 2018',
      authors: 'Mingmin Zhao, Yonglong Tian, Hang Zhao, Mohammad Alsheikh, Tianhong Li, Rumen Hristov, Zachary Kabelac, Dina Katabi, Antonio Torralba',
      description: '',
      paper_link: 'https://dl.acm.org/citation.cfm?id=3230579',
      project_link: 'http://news.mit.edu/2018/artificial-intelligence-senses-people-through-walls-0612',
      image: 'rf-pose-3d.png',
    }, 
    {
      title: 'Through-Wall Human Pose Estimation Using Radio Signals',
      publisher: 'CVPR 2018',
      authors: 'Mingmin Zhao, Tianhong Li, Mohammad Alsheikh, Yonglong Tian, Hang Zhao, Antonio Torralba, Dina Katabi',
      description: 'Superman vision: Seeing human pose through the wall!',
      paper_link: 'https://openaccess.thecvf.com/content_cvpr_2018/papers/Zhao_Through-Wall_Human_Pose_CVPR_2018_paper.pdf',
      project_link: 'http://rfpose.csail.mit.edu/',
      image: 'rf-pose.png',
      tags: [
        'hot',
      ],
    },
    // {
    //   title: 'Open Vocabulary Scene Parsing',
    //   publisher: 'ICCV 2017',
    //   authors: 'Hang Zhao, Xavier Puig, Bolei Zhou, Sanja Fidler, Antonio Torralba',
    //   description: '',
    //   paper_link: 'http://openaccess.thecvf.com/content_ICCV_2017/papers/Zhao_Open_Vocabulary_Scene_ICCV_2017_paper.pdf',
    //   project_link: 'http://sceneparsing.csail.mit.edu/openvoc/',
    //   image: 'openvoc.png',
    // }, 
    {
      title: 'Scene Parsing through ADE20K Dataset',
      publisher: 'CVPR 2017',
      authors: 'Bolei Zhou, Hang Zhao, Xavier Puig, Sanja Fidler, Adela Barriuso, Antonio Torralba',
      description: '"The most widely used scene parsing dataset."',
      paper_link: 'http://people.csail.mit.edu/bzhou/publication/scene-parse-camera-ready.pdf',
      code_link: 'https://github.com/CSAILVision/semantic-segmentation-pytorch',
      extra_link: [
        {
          name: 'Paper (IJCV 2018)',
          link: 'https://link.springer.com/article/10.1007/s11263-018-1140-0',
        },
        {
          name: 'Full Dataset',
          link: 'http://groups.csail.mit.edu/vision/datasets/ADE20K/',
        },
        {
          name: 'MIT Scene Parsing Benchmark',
          link: 'http://sceneparsing.csail.mit.edu/',
        },
      ],
      image: 'sceneparsing_cvpr2017.png',
      tags: [
        'hot',
      ],
    }, 
    {
      title: 'Loss Functions for Neural Networks for Image Processing',
      publisher: 'IEEE TCI 2017',
      authors: 'Hang Zhao, Orazio Gallo, Iuri Frosio and Jan Kautz',
      description: '',
      paper_link: 'http://ieeexplore.ieee.org/iel7/6745852/6960042/07797130.pdf',
      project_link: 'http://research.nvidia.com/publication/loss-functions-image-restoration-neural-networks',
      image: 'lossNN.png',
      tags: [
        'hot',
      ],
    }, 
    {
      title: 'Duckietown: an Open, Inexpensive and Flexible Platform for Autonomy Education and Research',
      publisher: 'ICRA 2017',
      authors: '',
      description: '"We are building an open-source education and research platform for autonomous driving."',
      paper_link: 'http://people.csail.mit.edu/hangzhao/papers/duckietown.pdf',
      project_link: 'https://duckietown.mit.edu/',
      image: 'duckietown.png',
    }, 
    {
      title: 'Unbounded High Dynamic Range Photography using a Modulo Camera',
      publisher: 'ICCP 2015 Best Paper Runner-up',
      authors: 'Hang Zhao, Boxin Shi, Christy Fernandez-Cull, Sai-Kit Yeung and Ramesh Raskar',
      description: '',
      paper_link: 'http://people.csail.mit.edu/hangzhao/papers/moduloUHDR.pdf',
      project_link: 'http://web.media.mit.edu/~hangzhao/modulo.html',
      image: 'moduloHDR.png',
      tags: [
        'hot',
      ],
    }, 
    // {
    //   title: '',
    //   publisher: '',
    //   authors: '',
    //   description: '',
    //   paper_link: '',
    //   project_link: '',
    //   image: '',
    // }, 
  ],
  
  publications: [
    {
      title: 'What Happened 3 Seconds Ago? Inferring the Past with Thermal Imaging',
      publisher: 'CVPR 2023',
      authors: 'Zitian Tang, Wenjie Ye, Wei-Chiu Ma, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2304.13651',
    },
    {
      title: 'ViP3D: End-to-end Visual Trajectory Prediction via 3D Agent Queries',
      publisher: 'CVPR 2023',
      authors: 'Junru Gu, Chenxu Hu, Tianyuan Zhang, Xuanyao Chen, Yilun Wang, Yue Wang, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2208.01582',
    },
    {
      title: 'Neural Map Prior for Autonomous Driving',
      publisher: 'CVPR 2023',
      authors: 'Xuan Xiong, Yicheng Liu, Tianyuan Yuan, Yilun Wang, Yue Wang, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2304.08481',
    },
    {
      title: 'GeoMAE: Masked Geometric Target Prediction for Self-supervised Point Cloud Pre-Training',
      publisher: 'CVPR 2023',
      authors: 'Xiaoyu Tian, Haoxi Ran, Yue Wang, Hang Zhao',
      paper_link: '',
    },
    {
      title: 'What Happened 3 Seconds Ago? Inferring the Past with Thermal Imaging',
      publisher: 'CVPR 2023',
      authors: 'Zitian Tang, Wenjie Ye, Wei-Chiu Ma, Hang Zhao',
      paper_link: '',
    },
    {
      title: 'SparseViT: Revisiting Activation Sparsity for Efficient High-Resolution Vision Transformer',
      publisher: 'CVPR 2023',
      authors: 'Xuanyao Chen, Zhijian Liu, Haotian Tang, Li Yi, Hang Zhao, Song Han',
      paper_link: 'https://arxiv.org/abs/2303.17605',
    },
    {
      title: 'The Modality Focusing Hypothesis: Towards Understanding Crossmodal Knowledge Distillation',
      publisher: 'ICLR 2023 Oral Top 5\%',
      authors: 'Zihui Xue, Zhengqi Gao, Sucheng Ren, Hang Zhao',
      paper_link: 'https://openreview.net/pdf?id=w0QXrZ3N-s',
    },
    {
      title: 'Programmatically Grounded, Compositionally Generalizable Robotic Manipulation',
      publisher: 'ICLR 2023 Oral Top 25\%',
      authors: 'Renhao Wang, Jiayuan Mao, Joy Hsu, Hang Zhao, Jiajun Wu, Yang Gao',
      paper_link: 'https://openreview.net/pdf?id=rZ-wylY5VI',
    },
    {
      title: 'Self-supervision through Random Segments with Autoregressive Coding (RandSAC)',
      publisher: 'ICLR 2023',
      authors: 'Tianyu Hua, Yonglong Tian, Sucheng Ren, Michalis Raptis, Hang Zhao, Leonid Sigal',
      paper_link: 'https://openreview.net/pdf?id=Ubc74gTVo3',
    },
    {
      title: 'VectorMapNet: End-to-end Vectorized HD Map Learning',
      publisher: 'Preprint 2022',
      authors: 'Yicheng Liu, Yue Wang, Yilun Wang, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2206.08920',
    },
    {
      title: 'InterSim: Interactive Traffic Simulation via Explicit Relation Modeling',
      publisher: 'IROS 2022',
      authors: 'Qiao Sun, Xin Huang, Brian C Williams, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2210.14413',
    }, 
    {
      title: 'CYBORGS: Contrastively Bootstrapping Object Representations by Grounding in Segmentation',
      publisher: 'ECCV 2022',
      authors: 'Renhao Wang, Hang Zhao, Yang Gao',
      paper_link: 'https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136910251.pdf',
    }, 
    {
      title: 'Learning Visual Styles from Audio-Visual Associations',
      publisher: 'ECCV 2022',
      authors: 'Tingle Li, Yichen Liu, Andrew Owens, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2205.05072',
    }, 
    {
      title: 'Radio2Speech: High Quality Speech Recovery from Radio Frequency Signals',
      publisher: 'Interspeech 2022',
      authors: 'Running Zhao, Jiangtao Yu, Tingle Li, Hang Zhao*, Edith C.H. Ngai*',
      paper_link: 'https://arxiv.org/abs/2206.11066',
    },
    {
      title: 'Sound2Synth: Interpreting Sound via FM Synthesizer Parameters Estimation',
      publisher: 'IJCAI 2022',
      authors: 'Zui Chen, Yansen Jing, Shengcheng Yuan, Yifei Xu, Jian Wu, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2205.03043',
    },
    {
      title: 'AutoAlign: Pixel-Instance Feature Aggregation for Multi-Modal 3D Object Detection',
      publisher: 'IJCAI 2022',
      authors: 'Zehui Chen, Zhenyu Li, Shiquan Zhang, Liangji Fang, Qinghong Jiang, Feng Zhao, Bolei Zhou, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2201.06493',
    },
    {
      title: 'FUTR3D: A Unified Sensor Fusion Framework for 3D Detection',
      publisher: 'Preprint 2022',
      authors: 'Xuanyao Chen, Tianyuan Zhang, Yue Wang, Yilun Wang, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2203.10642',
    }, 
    {
      title: 'MUTR3D: A Multi-camera Tracking Framework via 3D-to-2D Queries',
      publisher: 'CVPR Workshop on Autonomous Driving 2022',
      authors: 'Tianyuan Zhang, Xuanyao Chen, Yue Wang, Yilun Wang, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2205.00613',
    },
    {
      title: 'M2I: From Factored Marginal Trajectory Prediction to Interactive Prediction',
      publisher: 'CVPR 2022',
      authors: 'Qiao Sun, Xin Huang, Junru Gu, Brian C Williams, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2202.11884',
    },
    {
      title: 'Co-advise: Cross Inductive Bias Distillation',
      publisher: 'CVPR 2022',
      authors: 'Sucheng Ren, Zhengqi Gao, Tianyu Hua, Zihui Xue, Yonglong Tian, Shengfeng He, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2106.12378',
    },
    {
      title: 'Embracing Single Stride 3D Object Detector with Sparse Transformer',
      publisher: 'CVPR 2022',
      authors: 'Lue Fan, Ziqi Pang, Tianyuan Zhang, Yu-Xiong Wang, Hang Zhao, Feng Wang, Naiyan Wang, Zhaoxiang Zhang',
      paper_link: 'https://arxiv.org/abs/2112.06375',
    },
    {
      title: 'Egocentric Prediction of Action Target in 3D',
      publisher: 'CVPR 2022',
      authors: 'Yiming Li, Ziang Cao, Andrew Liang, Benjamin Liang, Luoyao Chen, Hang Zhao, Chen Feng',
      paper_link: 'https://openaccess.thecvf.com/content/CVPR2022/papers/Li_Egocentric_Prediction_of_Action_Target_in_3D_CVPR_2022_paper.pdf',
    },
    {
      title: 'HDMapNet: An Online HD Map Construction and Evaluation Framework',
      publisher: 'ICRA 2022, CVPR 2021 Workshop best paper nominee',
      authors: 'Qi Li, Yue Wang, Yilun Wang, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2107.06307',
    },
    {
      title: 'SEMI: Self-supervised Exploration via Multisensory Incongruity',
      publisher: 'ICRA 2022',
      authors: 'Jianren Wang*, Ziwen Zhuang*, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2009.12494',
    }, 
    {
      title: 'Depth Estimation Matters Most: Improving Per-Object Depth Estimation for Monocular 3D Detection and Tracking',
      publisher: 'ICRA 2022',
      authors: 'Longlong Jing, Ruichi Yu, Henrik Kretzschmar, Kang Li, Ruizhongtai Qi, Hang Zhao, Alper Ayvaci, Xu Chen, Dillon Cower, Yingwei Li, Yurong You, Han Deng, Congcong Li, Dragomir Anguelov',
      paper_link: 'https://ieeexplore.ieee.org/document/9811749',
    },  
    {
      title: 'Intrinsically Motivated Self-supervised Learning in Reinforcement Learning',
      publisher: 'ICRA 2022',
      authors: 'Yue Zhao, Chenzhuang Du, Hang Zhao, Tiejun Li',
      paper_link: 'https://ieeexplore.ieee.org/document/9812213/',
    },  
    {
      title: 'R4D: Utilizing Reference Objects for Long-Range Distance Estimation',
      publisher: 'ICLR 2022',
      authors: 'Yingwei Li, Tiffany Chen, Maya Kabkab, Ruichi Yu, Longlong Jing, Yurong You, Hang Zhao',
      paper_link: 'https://openreview.net/forum?id=MQ2sAGunyBP',
    },  
    {
      title: 'IFR-Explore: Learning Inter-object Functional Relationships in 3D Indoor Scenes',
      publisher: 'ICLR 2022',
      authors: 'Qi Li, Kaichun Mo, Yanchao Yang, Hang Zhao, Leonidas Guibas',
      paper_link: 'https://arxiv.org/abs/2112.05298?context=cs',
    }, 
    {
      title: 'SimIPU: Simple 2D Image and 3D Point Cloud Unsupervised Pre-Training for Spatial-Aware Visual Representations',
      publisher: 'AAAI 2022',
      authors: 'Zhenyu Li, Zehui Chen, Ang Li, Liangji Fang, Qinhong Jiang, Xianming Liu, Junjun Jiang, Bolei Zhou, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2112.04680',
    },
    {
      title: 'Neural Dubber: Dubbing for Videos According to Scripts',
      publisher: 'NeurIPS 2021',
      authors: 'Chenxu Hu, Qiao Tian, Tingle Li, Yuping Wang, Yuxuan Wang, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2110.08243',
    },
    {
      title: 'What Makes Multi-Modal Learning Better than Single (Provably)',
      publisher: 'NeurIPS 2021',
      authors: 'Yu Huang, Chenzhuang Du, Zihui Xue, Xuanyao Chen, Hang Zhao, Longbo Huang',
      paper_link: 'https://proceedings.neurips.cc/paper/2021/hash/5aa3405a3f865c10f420a4a7b55cbff3-Abstract.html',
    },
    {
      title: 'DETR3D: 3D Object Detection from Multi-view Images via 3D-to-2D Queries',
      publisher: 'CoRL 2021',
      authors: 'Yue Wang, Vitor Campagnolo Guizilini, Tianyuan Zhang, Yilun Wang, Hang Zhao, Justin Solomon',
      paper_link: 'https://openreview.net/pdf?id=xHnJS2GYFDz',
    },
    {
      title: 'Adversarially Robust Imitation Learning',
      publisher: 'CoRL 2021',
      authors: 'Jianren Wang, Ziwen Zhuang, Yuyang Wang, Hang Zhao',
      paper_link: 'https://openreview.net/pdf?id=9aVCUv3nKBg',
    },
    {
      title: 'Multi-Agent Trajectory Prediction by Combining Egocentric and Allocentric Views',
      publisher: 'CoRL 2021',
      authors: 'Xiaosong Jia, Liting Sun, Hang Zhao, Masayoshi Tomizuka, Wei Zhan',
      paper_link: 'https://proceedings.mlr.press/v164/jia22a.html',
    },
    {
      title: 'On Feature Decorrelation in Self-Supervised Learning',
      publisher: 'ICCV 2021 Oral',
      authors: 'Tianyu Hua, Wenxiao Wang, Zihui Xue, Yue Wang, Sucheng Ren, Hang Zhao',
      paper_link: 'https://openaccess.thecvf.com/content/ICCV2021/html/Hua_On_Feature_Decorrelation_in_Self-Supervised_Learning_ICCV_2021_paper.html',
    },
	  {
      title: 'Large Scale Interactive Motion Forecasting for Autonomous Driving: The Waymo Open Motion Dataset',
      publisher: 'ICCV 2021 Oral',
      authors: 'Scott Ettinger, Shuyang Cheng, Benjamin Caine, Chenxi Liu, Hang Zhao, Sabeek Pradhan, Yuning Chai, Ben Sapp, Charles Qi, Yin Zhou, Zoey Yang, Aurelien Chouard, Pei Sun, Jiquan Ngiam, Vijay Vasudevan, Alexander McCauley, Jonathon Shlens, Dragomir Anguelov',
      paper_link: 'https://openaccess.thecvf.com/content/ICCV2021/html/Ettinger_Large_Scale_Interactive_Motion_Forecasting_for_Autonomous_Driving_The_Waymo_ICCV_2021_paper.html',
    },
    {
      title: 'Multimodal Knowledge Expansion',
      publisher: 'ICCV 2021',
      authors: 'Zihui Xue, Sucheng Ren, Zhengqi Gao, Hang Zhao',
      paper_link: 'https://openaccess.thecvf.com/content/ICCV2021/html/Xue_Multimodal_Knowledge_Expansion_ICCV_2021_paper.html',
    },
    {
      title: 'DenseTNT: End-to-end Trajectory Prediction from Dense Goal Sets',
      publisher: 'ICCV 2021',
      authors: 'Junru Gu, Chen Sun, Hang Zhao',
      paper_link: 'https://openaccess.thecvf.com/content/ICCV2021/html/Gu_DenseTNT_End-to-End_Trajectory_Prediction_From_Dense_Goal_Sets_ICCV_2021_paper.html',
    },
    {
      title: 'DenseTNT: Waymo Open Dataset Motion Prediction Challenge 1st Place Solution',
      publisher: 'CVPR 2021 Workshop, Waymo Open Dataset Challenge Winner',
      authors: 'Junru Gu, Qiao Sun, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2106.14160',
    },
    {
      title: 'CVC: Contrastive Learning for Non-parallel Voice Conversion',
      publisher: 'Interspeech 2021 (ISCA travel grant award)',
      authors: 'Tingle Li, Yichen Liu, Chenxu Hu, Hang Zhao',
      paper_link: 'https://www.isca-speech.org/archive/interspeech_2021/li21d_interspeech.html',
    },
    {
      title: 'HDMapGen: A Hierarchical Graph Generative Model of High Definition Maps',
      publisher: 'CVPR 2021',
      authors: 'Lu Mi, Hang Zhao, Charlie Nash, Xiaohan Jin, Jiyang Gao, Chen Sun, Cordelia Schmid, Nir Shavit, Yuning Chai, Dragomir Anguelov',
      paper_link: 'https://openaccess.thecvf.com/content/CVPR2021/html/Mi_HDMapGen_A_Hierarchical_Graph_Generative_Model_of_High_Definition_Maps_CVPR_2021_paper.html',
    },
    {
      title: 'TNT: Target-driveN Trajectory Prediction',
      publisher: 'CoRL 2020',
      authors: 'Hang Zhao*, Jiyang Gao*, Tian Lan, Chen Sun, Benjamin Sapp, Balakrishnan Varadarajan, Yue Shen, Yi Shen, Yuning Chai, Cordelia Schmid, Congcong Li, Dragomir Anguelov',
      paper_link: 'https://arxiv.org/abs/2008.08294',
    },
    {
      title: 'CLOUD: Contrastive Learning of Unsupervised Dynamics',
      publisher: 'CoRL 2020',
      authors: 'Jianren Wang, Yujie Lu, Hang Zhao',
      paper_link: 'https://arxiv.org/abs/2010.12488',
    }, 
    {
      title: 'Unsupervised Monocular Depth Learning in Dynamic Scenes',
      publisher: 'CoRL 2020',
      authors: 'Hanhan Li, Ariel Gordon, Hang Zhao, Vincent Casser, Anelia Angelova',
      paper_link: 'https://arxiv.org/abs/2010.16404',
    }, 
    {
      title: 'UnModNet: Learning to Unwrap a Modulo Image for High Dynamic Range Imaging',
      publisher: 'NeuRIPS 2020',
      authors: 'Chu Zhou, Hang Zhao, Jin Han, Chang Xu, Chao Xu, Tiejun Huang, Boxin Shi',
      paper_link: 'https://proceedings.neurips.cc/paper/2020/hash/1102a326d5f7c9e04fc3c89d0ede88c9-Abstract.html',
    },
    {
      title: 'VectorNet: Encoding HD Maps and Agent Dynamics from Vectorized Representation',
      publisher: 'CVPR 2020',
      authors: 'Jiyang Gao, Chen Sun, Hang Zhao, Yi Shen, Dragomir Anguelov, Congcong Li, Cordelia Schmid',
      paper_link: 'https://openaccess.thecvf.com/content_CVPR_2020/papers/Gao_VectorNet_Encoding_HD_Maps_and_Agent_Dynamics_From_Vectorized_Representation_CVPR_2020_paper.pdf',
    },
    {
      title: 'Scalability in Perception for Autonomous Driving: Waymo Open Dataset',
      publisher: 'CVPR 2020',
      authors: 'Pei Sun, Henrik Kretzschmar, Xerxes Dotiwalla, Aurelien Chouard, Vijaysai Patnaik, Paul Tsui, James Guo, Yin Zhou, Yuning Chai, Benjamin Caine, Vijay Vasudevan, Wei Han, Jiquan Ngiam, Hang Zhao, Aleksei Timofeev, Scott Ettinger, Maxim Krivokon, Amy Gao, Aditya Joshi, Sheng Zhao, Shuyang Cheng, Yu Zhang, Jonathon Shlens, Zhifeng Chen, Dragomir Anguelov',
      paper_link: 'https://arxiv.org/abs/1912.04838',
    },
    {
      title: 'Music Gesture for Visual Sound Separation',
      publisher: 'CVPR 2020',
      authors: 'Chuang Gan, Deng Huang, Hang Zhao, Joshua B Tenenbaum, Antonio Torralba',
      paper_link: 'https://openaccess.thecvf.com/content_CVPR_2020/html/Gan_Music_Gesture_for_Visual_Sound_Separation_CVPR_2020_paper.html',
    },
    {
      title: 'AlignNet: A Unifying Approach to Audio-visual Alignment',
      publisher: 'WACV 2020',
      authors: 'Jianren Wang, Zhaoyuan Fang, Hang Zhao',
      paper_link: 'https://openaccess.thecvf.com/content_WACV_2020/html/Wang_AlignNet_A_Unifying_Approach_to_Audio-Visual_Alignment_WACV_2020_paper.html'
    },
    {
      title: 'The Sound of Motions',
      publisher: 'ICCV 2019',
      authors: 'Hang Zhao, Chuang Gan, Wei-Chiu Ma, Antonio Torralba',
      paper_link: 'https://arxiv.org/abs/1904.05979',
    },
    {
      title: 'Self-supervised Moving Vehicle Tracking with Stereo Sound',
      publisher: 'ICCV 2019',
      authors: 'Chuang Gan, Hang Zhao, Peihao Chen, David Cox, Antonio Torralba',
      paper_link: 'http://openaccess.thecvf.com/content_ICCV_2019/html/Gan_Self-Supervised_Moving_Vehicle_Tracking_With_Stereo_Sound_ICCV_2019_paper.html',
    }, 
    {
      title: 'Through-Wall Human Mesh Recovery Using Radio Signals',
      publisher: 'ICCV 2019',
      authors: 'Mingmin Zhao, Yingcheng Liu, Aniruddh Raghu, Hang Zhao, Tianhong Li, Antonio Torralba, Dina Katabi',
      paper_link: 'http://openaccess.thecvf.com/content_ICCV_2019/html/Zhao_Through-Wall_Human_Mesh_Recovery_Using_Radio_Signals_ICCV_2019_paper.html',
    }, 
    {
      title: 'HACS: Human Action Clips and Segments Dataset for Recognition and Temporal Localization',
      publisher: 'ICCV 2019',
      authors: 'Hang Zhao, Zhicheng Yan, Lorenzo Torresani, Antonio Torralba',
      paper_link: 'https://arxiv.org/abs/1712.09374',
    }, 
    {
      title: 'Self-Supervised Audio-visual Co-segmentation',
      publisher: 'ICASSP 2019',
      authors: 'Andrew Rouditchenko*, Hang Zhao*, Chuang Gan, Josh McDermott, Antonio Torralba',
      paper_link: 'https://arxiv.org/abs/1904.09013',
    }, 
    {
      title: 'The Sound of Pixels',
      publisher: 'ECCV 2018',
      authors: 'Hang Zhao, Chuang Gan, Andrew Rouditchenko, Carl Vondrick, Josh McDermott, Antonio Torralba',
      paper_link: 'https://arxiv.org/abs/1804.03160',
    }, 
    {
      title: 'RF-Based 3D Skeletons',
      publisher: 'SIGCOMM 2018',
      authors: 'Mingmin Zhao, Yonglong Tian, Hang Zhao, Mohammad Alsheikh, Tianhong Li, Rumen Hristov, Zachary Kabelac, Dina Katabi, Antonio Torralba',
      paper_link: 'https://dl.acm.org/citation.cfm?id=3230579',
    }, 
    {
      title: 'Through-Wall Human Pose Estimation Using Radio Signals',
      publisher: 'CVPR 2018',
      authors: 'Mingmin Zhao, Tianhong Li, Mohammad Alsheikh, Yonglong Tian, Hang Zhao, Antonio Torralba, Dina Katabi',
      paper_link: '',
    },
    {
      title: 'Semantic Understanding of Scenes through the ADE20K Dataset',
      publisher: 'IJCV 2018',
      authors: 'Bolei Zhou, Hang Zhao, Xavier Puig, Tete Xiao, Sanja Fidler, Adela Barriuso, Antonio Torralba',
      paper_link: 'https://link.springer.com/article/10.1007/s11263-018-1140-0',
    }, 
    {
      title: 'Open Vocabulary Scene Parsing',
      publisher: 'ICCV 2017',
      authors: 'Hang Zhao, Xavier Puig, Bolei Zhou, Sanja Fidler, Antonio Torralba',
      paper_link: 'http://openaccess.thecvf.com/content_ICCV_2017/papers/Zhao_Open_Vocabulary_Scene_ICCV_2017_paper.pdf',
    }, 
    {
      title: 'Scene Parsing through ADE20K Dataset',
      publisher: 'CVPR 2017',
      authors: 'Bolei Zhou, Hang Zhao, Xavier Puig, Sanja Fidler, Adela Barriuso, Antonio Torralba',
      paper_link: 'http://people.csail.mit.edu/bzhou/publication/scene-parse-camera-ready.pdf',
    }, 
    {
      title: 'Loss Functions for Neural Networks for Image Processing',
      publisher: 'IEEE TCI 2017',
      authors: 'Hang Zhao, Orazio Gallo, Iuri Frosio and Jan Kautz',
      paper_link: 'http://ieeexplore.ieee.org/iel7/6745852/6960042/07797130.pdf',
    }, 
    {
      title: 'Duckietown: an Open, Inexpensive and Flexible Platform for Autonomy Education and Research',
      publisher: 'ICRA 2017',
      authors: 'Liam Paul, et al.',
      paper_link: 'http://people.csail.mit.edu/hangzhao/papers/duckietown.pdf',
    }, 
    {
      title: 'Unbounded High Dynamic Range Photography using a Modulo Camera',
      publisher: 'ICCP 2015 Best Paper Runner-up',
      authors: 'Hang Zhao, Boxin Shi, Christy Fernandez-Cull, Sai-Kit Yeung and Ramesh Raskar',
      paper_link: 'http://people.csail.mit.edu/hangzhao/papers/moduloUHDR.pdf',
    }, 
    {
      title: 'Snapshot on-chip HDR ROIC architectures',
      publisher: 'COSI 2015',
      authors: 'Christy Fernandez-Cull, Hang Zhao, Boxin Shi, Brian M. Tyrrell, Joseph Lin and Ramesh Raskar',
      paper_link: 'https://www.osapublishing.org/abstract.cfm?uri=COSI-2015-CM3E.3',
    }, 
    {	
      title: 'Occluded imaging with time of flight sensors',
      publisher: 'ACM Transactions on Graphics 2015',
      authors: 'Achuta Kadambi, Hang Zhao, Boxin Shi and Ramesh Raskar',
      paper_link: 'https://dl.acm.org/doi/abs/10.1145/2836164',
    }, 
    {
      title: 'Sub-pixel layout for super-resolution with images in an octic group',
      publisher: 'ECCV 2014',
      authors: 'Boxin Shi, Hang Zhao, Moshe Ben-Ezra, Sai-Kit Yeung, Christy Fernandez-Cull, R. Hamilton Shepard, Christopher Barsi, Ramesh Raskar',
      paper_link: 'https://link.springer.com/chapter/10.1007/978-3-319-10590-1_17',
    }, 
    // {
    //   title: '',
    //   publisher: '',
    //   authors: '',
    //   paper_link: '',
    // }, 
  ],
  
  join_us: {
    title: 'We are globally hiring top talents to join us.',
    content: [
      {
        agent_type: 'PostDoc/PhD/BS Students',
        description: 'If you would like to join our lab as a student. Please directly send your resume and transcript to Prof. Hang Zhao.',
      },
      {
        agent_type: 'Research Assistants',
        description: 'If you want to spend your gap year as a full-time (paid) research assistant in our lab. Please directly send your resume and transcript to Prof. Hang Zhao.',
      },
      {
        agent_type: 'Engineers',
        description: 'We have full-time engineer positions in our lab, related to autonomous driving and robotics. Please directly send your resume to Prof. Hang Zhao.',
      },
    ],
  },
}

export default main
